print ('hello world')
print('5')
print(type('5'))
print("ala ma kota, kot ma ale")
print('Ala powiedziala: "on jest moj"')
print("Tomek powiedzial ze: \"on jest moj\"")
print ("""Adam powiedział "no way" """)
print ("c:\dey2")
print(r"c:\back\moje\torenty")
